#ifndef _H_PCAP_UTIL
#define _H_PCAP_UTIL

#include <stdint.h>
#include <stdbool.h>
#include "common.h"

/**
 * @brief Compile a tcpdump/pcap filter expression to classic BPF and store it
 * in `out` (as struct pcap_filter, zero-initialized). Uses DLT_EN10MB so the
 * generated bytecode assumes an Ethernet-framed packet, matching XDP ingress.
 * @param expr The pcap filter expression, e.g. "ip6 and dst host 2001:db8::1".
 * @param out  Destination filter (len set to instruction count on success).
 * @return 0 on success, -1 on failure (message printed to stderr).
 */
int compile_pcap_filter(const char *expr, struct pcap_filter *out);

#endif // _H_PCAP_UTIL
